services:
  checking-projections:
    build: .
    container_name: checking-projections
    volumes:
      - ./data:/app/data
      - ./config:/app/config
      - ./secrets:/app/secrets
    restart: unless-stopped
    env_file:
      - ./config/.env
    environment:
      - TZ=America/New_York
